### ISSUE TITLE
Is this integration dead?

### ISSUE THREAD

**Issue by curt7000** [konnected-io/noonlight-hass#17]
I would really like to include my Freeze and Water sensors into this service.  It appears development on API v2 has stopped.  Is this integration dead and should Noonlight customers move to a different service?  Thanks

**Comment by saxopwn** [comment]
Still worked for me as of October

**Comment by curt7000** [comment]
The integration still works but there appears to be zero development.

**Comment by iloveicedgreentea** [comment]
I will do my best to take this on. I use this so its important to me it continues to work. Feel free to follow progress here https://discord.gg/ud7B8XuDmy

Not sure when, but its definitely important to me that this keeps working

**Comment by Snuffy2** [comment]
Funny, I was going to post something here in a day or 2. I'm mostly done with adding a config flow for noonlight and was gonna make some other tweaks from there. @iloveicedgreentea, happy to work together if interested. 

https://github.com/Snuffy2/noonlight-hass

**Comment by iloveicedgreentea** [comment]
yeah we should definitely make it an official integration. Feel free to reach out on discord I would like to collaborate on it

**Comment by curt7000** [comment]
Would love for this to become an official integration!  Happy to support testing where I can.

Note: I recall Home Assistant had denied it becoming an official integration because the integration's purpose was to deliver a paid service via Home Assistant ... or something like that.

**Comment by snicker** [comment]
Hey all- will be making some updates in the coming days. We were not able to get this integrated as an official part of Home Assistant in the past, but it may be worth re-opening the discussion again now that some time has passed.
