### ISSUE TITLE
Can't read json

### ISSUE THREAD

**Issue by dilscallion** [konnected-io/noonlight-hass#4]
I'm getting the following errors when I install and reboot using HACS. Any help would be much appreciated.
`
20-06-22 17:18:17 INFO (MainThread) [supervisor.store.git] Clone add-on https://github.com/konnected-io/noonlight-hass repository
20-06-22 17:18:19 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/4b956b7e/repository.json: [Errno 2] No such file or directory: '/data/addons/git/4b956b7e/repository.json'
20-06-22 17:18:19 WARNING (MainThread) [supervisor.store.data] Can't read repository information from /data/addons/git/4b956b7e/repository.json
20-06-22 17:18:19 INFO (MainThread) [supervisor.store] Load add-ons from store: 65 all - 0 new - 0 remove
20-06-22 17:19:57 INFO (MainThread) [supervisor.store.git] Remove custom add-on repository https://github.com/konnected-io/noonlight-hass
`

**Comment by snicker** [comment]
closing, this seems to be an error with HACS rather than the Noonlight integration. Please re-open if error is still occuring.
