### ISSUE TITLE
No 'version' key in the manifest file - integration will not load in latest HASS version

### ISSUE THREAD

**Issue by peetipablo** [konnected-io/noonlight-hass#6]
`2021-05-08 09:43:50 WARNING (MainThread) [homeassistant.loader] No 'version' key in the manifest file for custom integration 'noonlight'. As of Home Assistant 2021.6, this integration will no longer be loaded. Please report this to the maintainer of 'noonlight'`

This custom component for HASS needs to be updated to include a version key, or else it will not load with home assistant version 2021.6.

**Comment by ragaimeena** [comment]
please update the version key

**Comment by curt7000** [comment]
Yep, moonlight breaks under 2021.6.  Please update.

**Comment by pageb018** [comment]
Just a heads up, you can fix this by adding 

"version": "1.0" to your noonlight manifest file. Located at /config/custom_components/noonlight/manifest.json

Example: 

{
  "domain": "noonlight",
  "name": "Noonlight",
  "documentation": "https://github.com/konnected-io/noonlight-hass",
  **"version": "1.0",**
  "requirements": [
    "noonlight==0.1.1"
  ],
  "dependencies": [
    "http"
  ],
  "codeowners": [
    "@heythisisnate",
	"@snicker"
  ]
}
